### PR TITLE
Update Place Tørring

### PR DESCRIPTION
**Pull request by stepps00**
Updating `data/101/805/585/101805585.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by stepps00** [comment]
https://www.wikidata.org/wiki/Q2183058 Updates names for Torring, DK.

**Number of records updated**: 1

**Review by nvkelso — COMMENTED** [review]
Is the first word just wrong? Should it be preserved as variant name in at least 1 language?

**Comment by stepps00** [comment]
The names were removed instead of being stored as variants because they seem to reference a person: 

- https://www.wikidata.org/wiki/Q1368476
- https://en.wikipedia.org/wiki/Jesper_T%C3%B8rring

I'm not totally sure how these names were introduced in the first place, but suspect they come from a wikidata/wikipedia run to add names (concordances look correct, though). So I'd recommend we remove rather than store since this is a data quality issue.

**Comment by nvkelso** [comment]
Looks like we fixed the concordance earlier, and yes that's just bad data so OK to remove.

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
